/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacaocaixademercado;

import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class VendaUI extends javax.swing.JFrame {

    /**
     * Creates new form CaixaUIMain
     */
    private Registradora refRegistradora;
    private CaixaMainUI refCaixaMainUI;
    
    
    public VendaUI(Registradora refRegistradora, CaixaMainUI CaixaUI) {
        refCaixaMainUI = CaixaUI;
        this.refRegistradora = refRegistradora;
        initComponents();
    }
    public VendaUI() {       
     
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtListaCompra = new javax.swing.JTextArea();
        botaoInsereNaLista = new javax.swing.JButton();
        botaoConcluirVenda = new javax.swing.JButton();
        botaoPagamento = new javax.swing.JButton();
        txtCodBarra = new javax.swing.JFormattedTextField();

        setTitle("Venda");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Insira o código de barras: ");

        jLabel2.setText("Digite a quantidade:");

        txtListaCompra.setEditable(false);
        txtListaCompra.setColumns(20);
        txtListaCompra.setRows(5);
        jScrollPane1.setViewportView(txtListaCompra);

        botaoInsereNaLista.setText("Inserir Item");
        botaoInsereNaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInsereNaListaActionPerformed(evt);
            }
        });

        botaoConcluirVenda.setText("Concluir Venda");
        botaoConcluirVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConcluirVendaActionPerformed(evt);
            }
        });

        botaoPagamento.setText("Pagamento");
        botaoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPagamentoActionPerformed(evt);
            }
        });

        try {
            txtCodBarra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoConcluirVenda)
                        .addGap(115, 115, 115)
                        .addComponent(botaoPagamento)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(botaoInsereNaLista))
                            .addComponent(txtCodBarra))))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoInsereNaLista)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoConcluirVenda)
                    .addComponent(botaoPagamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoInsereNaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInsereNaListaActionPerformed
        txtListaCompra.setText("");
        int codBarra = Integer.parseInt(txtCodBarra.getText());
        int qtd = Integer.parseInt(txtQtd.getText());
        txtListaCompra.append(refRegistradora.incluirItem(codBarra, qtd));
        txtCodBarra.setText("");
        txtQtd.setText("");
        txtCodBarra.requestFocusInWindow();
        //JOptionPane.showMessageDialog(null, codBarra);
    }//GEN-LAST:event_botaoInsereNaListaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        VendaUI.this.dispose();
        refCaixaMainUI.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void botaoConcluirVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConcluirVendaActionPerformed
        txtListaCompra.setText("");
        txtListaCompra.setText("Resumo da compra:\n" +
                refRegistradora.gerarResumoVenda()+ 
                "\n----------------------\n");
        txtListaCompra.append("Total: " + refRegistradora.concluirVenda());
    }//GEN-LAST:event_botaoConcluirVendaActionPerformed

    private void botaoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPagamentoActionPerformed
       PagamentoUI diagPagamento = new PagamentoUI(VendaUI.this, true,refRegistradora);
       diagPagamento.setVisible(true);
        System.out.println(refRegistradora.gerarResumoVenda());
       
    }//GEN-LAST:event_botaoPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConcluirVenda;
    private javax.swing.JButton botaoInsereNaLista;
    private javax.swing.JButton botaoPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField txtCodBarra;
    private javax.swing.JTextArea txtListaCompra;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables
}
